name: pipeline1

on:
    push:
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    practice-job1:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Run a one line script
              run: echo Hello world!
            - name: Run a multi line script
              run: |
                echo Add few line
                echo As theis is a multi line script
