name: practice_pipeline

on: 
    push:
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    practice_job1:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: multi line script
              run: echo Hello! this is line one
            - name: Line 2 of multi line script
              run: |
                echo this is line 2
                echo And this is line 3
